server:
  grpc_port: 50051

database:
  host: 147.45.157.73
  port: 5432
  user: gen_user
  password: A-RKTYC3y$=Bi1
  name: default_db
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 300

logging:
  level: info
  format: json


