server:
  grpc_port: 50051

database:
  host: 147.45.157.73
  port: 5432
  user: gen_user
  password: A-RKTYC3y$=Bi1
  name: default_db

cors:
  allow_origins:
    - "http://localhost:5173"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
  allow_credentials: true
  max_age: 43200 # 12 часов в секундах

logging:
  level: info
  format: json


