server:
  grpc_port: 50051

database:
  host: 147.45.157.73
  port: 5432
  user: gen_user
  password: A-RKTYC3y$=Bi1
  name: default_db

cors:
  allow_origins:
    - "http://localhost:5173"
    - "http://localhost:8083"
    - "http://localhost:8082"
    - "http://localhost:8084"
  allow_methods:
    - "GET"
    - "POST"
    - "PATCH"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Type"
    - "Accept"
    - "Authorization"
  expose_headers:
    "X-Is-Authenticated"
  allow_credentials: true
  max_age: 43200 # 12 часов в секундах

s3:
  bucket: 50d7c1c5-c7d4dfff-e316-40a1-8fde-a56e3a6362a8
  region: ru-1
  access_key: WQ23X0DWIE4YZI9AZ902
  secret_key: 2WBucNg4AhA8UNbkmA9qLB69hKEsjwoQ59X3qp1r
  endpoint: https://s3.timeweb.cloud

logging:
  level: info
  format: json

prometheus:
  global:
    scrape_interval: 15s
  scrape_configs:
    - job_name: 'collect_metrics'
      static_configs:
        - targets: ['localhost:8080']


